//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjLayoutAuth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moviebookingtable
    {
        public int BookingID { get; set; }
        public int ScreenID { get; set; }
        public int Noofseats { get; set; }
        public Nullable<int> Totalamount { get; set; }
    }
}
