//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudyEg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieBooking
    {
        public int BookingID { get; set; }
        public string Customer { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<int> TheaterID { get; set; }
        public Nullable<int> ScreenID { get; set; }
        public Nullable<int> NoofSeats { get; set; }
        public Nullable<int> TotalAmount { get; set; }
    
        public virtual Movie Movie { get; set; }
        public virtual Screen Screen { get; set; }
        public virtual Theater Theater { get; set; }
    }
}
