//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudyEg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Screen()
        {
            this.MovieBookings = new HashSet<MovieBooking>();
        }
    
        public int ScreenID { get; set; }
        public Nullable<int> MovieID { get; set; }
        public Nullable<int> TheaterID { get; set; }
        public Nullable<int> NOofSeats { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Movie Movie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieBooking> MovieBookings { get; set; }
        public virtual Theater Theater { get; set; }
    }
}
