//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDay2Assign.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBmovieEntities : DbContext
    {
        public DBmovieEntities()
            : base("name=DBmovieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Movietable> Movietables { get; set; }
        public virtual DbSet<Customertable> Customertables { get; set; }
        public virtual DbSet<Moviebookingtable> Moviebookingtables { get; set; }
        public virtual DbSet<Screentable> Screentables { get; set; }
        public virtual DbSet<Theatretable> Theatretables { get; set; }
    }
}
